UCPKN-3399: Update oe_content to 4.1.
openeuropa/oe_agenda pull request #11
Opened 2024-10-01 07:39 UTC by kp77

2024-11-22 06:56 UTC, drishu requested changes

2024-11-22 06:56 UTC, drishu commented on composer.json
> +        "openeuropa/oe_content": "^4.1"
we can't drop version 3, this is open source, we dont know if anybody else is using it so we have to support both major versions

2024-11-27 14:52 UTC, drishu approved these changes

2024-11-28 15:23 UTC, msnassar approved these changes

2024-11-29 08:25 UTC, merged